### ISSUE TITLE
Add to types repository

### ISSUE THREAD

**Issue by BugsBunnyBR** [Dominic-Preap/excel4node#1]
Hey, how about to add this to types repository?
Or at least give a readme of how to use this ?
thanks

**Comment by bobweil** [comment]
For my copy, I added the middle line in the snippet below to cover writing to the  Express Response:
`    write(filename: string): void;`
`    write(filename: string, res: Response): void;   // Added this.`
`    write(filename: string, callback: (err: any, stats: Stats) => void): void;`
