### ISSUE TITLE
Please add a license to the repository

### ISSUE THREAD

**Issue by ghost** [Dominic-Preap/excel4node#8]
First of all, thank you for creating these types!

Currently the repository doesn't have a license, and by default that makes the types not usable in other projects, according to GitHub docs:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and **no one may reproduce, distribute, or create derivative works from your work**.

Adding one would help everyone, and maybe it can help with https://github.com/advisr-io/excel4node/issues/64, which is a request to add types to the main repo (continued from the original issue where you commented before, in the now archived repo https://github.com/natergj/excel4node/issues/188) 🤞

Thanks!

**Comment by Dominic-Preap** [comment]
Done, thank for reminding.
